U_GRAPH_FILENAME = "u_graph.json"
EDGE_LIST_FILENAME = "edges.csv"
BITCOIN_DATASET_DIR = f"elliptic_bitcoin_dataset"
EDGELIST_FILE = f"elliptic_txs_edgelist.csv"
FEATURES_FILE = f"elliptic_txs_features.csv"
WORKING_DIR = f"/Users/markbentivegna/Documents/GWU/projects/bitcoin_fraud_detection"